### ISSUE TITLE
Regarding using index

### ISSUE THREAD

**Issue by jonyejin** [knowledgedefinednetworking/RouteNet-challenge#10]
Hello, I'm a participant for GNN 2023' Challenge.

**How do you gain access to dictionary, arrays regarding path or flow index?**

It seems that DataGenerator only returns Samples.

Thank you!

**Comment by CarlosGuemS** [comment]
Hello!

The Sample class acts as a wrapper for all the information within each sample, which represents one traffic scenario. Hence, to gain access to the data you described, you need to use the getter functions within this class:
```python
# sample is a Sample instance
network_topology = sample.get_physical_topology_object()
traffic_matrix = sample.get_traffic_matrix()
physical_path_matrix = sample.get_physical_path_matrix()
performance_matrix = sample.get_performance_matrix()
packet_info_matrix = sample.get_pkts_info_object()
````

If you haven't already, this is explained more in detail in the README document, specifically in the '["How-to" guide for modifying the code](https://github.com/BNN-UPC/GNNetworkingChallenge/tree/2023_RealNetworkDT#how-to-guide-for-modifying-the-code)' section.

Hope this helps!

**Comment by CarlosGuemS** [comment]
Hi!

If you don't have further inquiries, I'm closing this issue. Feel free to open it again if you do.

Best regards
