### ISSUE TITLE
`predict.py` causing errors

### ISSUE THREAD

**Issue by jonyejin** [knowledgedefinednetworking/RouteNet-challenge#12]
`ValueError: Unable to load weights saved in HDF5 format into a subclassed Model which has not created its variables yet. Call the Model first, then load the weights.`

This error occurs when I call predict.py directly.

**Comment by CarlosGuemS** [comment]
Hello!

I'll need some extra information to help you out:

- May you share the bash command where you call predict.py?
- May you share the entirety of the terminal output when calling predict.py?
- Have you done changes to the training or testing pipeline? If so, which?

**Comment by gblessed** [comment]
Hi I am also facing the same problem

**Comment by CarlosGuemS** [comment]
Hello,

I've tried to re-run the commands as described in the README and wasn't able to find the issue. Could you provide me with more details (i.e. the error message, if you made modifications to the code, which libraries did you use to build your solutions...).

Otherwise I will not be able to help you out.

**Comment by gblessed** [comment]
Ok I have followed the commands in the readme.

The error is this : ValueError: Unable to load weights saved in HDF5 format into a subclassed Model which has not created its variables yet. Call the Model first, then load the weights.

The error is in the line:  model.load_weights(args.ckpt_path) in predict.py

Even though the model is in the ckpt_path .. the files i have are : 
![image](https://github.com/BNN-UPC/GNNetworkingChallenge/assets/53085242/327e2f5f-e4c5-4fef-8949-c9dbc8037efa)

**Comment by gblessed** [comment]
The command I ran is : python3 /home/ec2-user/gnnet-ch23-dataset-cbr-mb/GNNetworkingChallenge-2023_RealNetworkDT/predict.py -ds CBR+MB --ckpt-path ckpt/Baseline_cbr_mb/best_08_10 --tr-path "gnnet-ch23-dataset-cbr-mb/extracted_08_10_cv/0/training" --te-path "/home/ec2-user/gnnet-ch23-dataset-cbr-mb/gnnet-ch23-toy-dataset/extracted_toy" --toy

**Comment by CarlosGuemS** [comment]
I think I know what the issue is: "--ckpt-path" should point to the specific checkpoint, not the folder it is in. Try using "--ckpt-path ckpt/Baseline_cbr_mb/best_08_10/22-41.9264" instead. Let me know if it works or the issue still persists.

**Comment by gblessed** [comment]
Yes, it has worked. Thanks !

**Comment by CarlosGuemS** [comment]
You're welcome, I'm glad it was solved!

@jonyejin Can you try to see if it works for you now?

**Comment by jonyejin** [comment]
It worked out for me too! Thanks to @CarlosGuemS  and @gblessed. I'll close the issue!
