### ISSUE TITLE
Traffic matrix extracted from simulation?

### ISSUE THREAD

**Issue by diegocervera** [knowledgedefinednetworking/RouteNet-challenge#8]
Hi,

I was having a look at the paper and the implementation and there is something I would like to understand a bit better. In [this paper](https://arxiv.org/abs/1901.08113), you describe the traffic matrix as the "bandwidth between each pair of nodes in the network". In [this other paper](https://arxiv.org/abs/1910.01508), the traffic matrix is defined as follows:
![image](https://user-images.githubusercontent.com/9992632/153560298-0012f536-fd08-4872-af90-4a0152bd52af.png)
being `TM(src, dst)` the traffic exchanged by every src-dst pair.

In the implementation I can see that you're loading the traffic matrix [here](https://github.com/BNN-UPC/GNNetworkingChallenge/blob/99d896afedd50405b23153ccc9e5625684b88dd9/code/read_dataset.py#L61), by using the `AvgBw` of the flow as described [here](https://github.com/BNN-UPC/datanetAPI/tree/challenge2021).

So I was wondering whether the `AvgBw` is an output of the simulation? Or is that calculated before the simulation (as described in the paper) and then used to generate the simulation?

Many thanks,
Diego

**Comment by jsuarezv** [comment]
Hello Diego,
Thank you for your interest in our research.
Just let you know that the code you are poinintg out has some slight differences with respect to the original model published at IEEE JSAC [[here](https://github.com/knowledgedefinednetworking/net2vec/tree/RouteNet-JSAC19/routenet)]. This code was prepared as a baseline solution for the GNNet challenge and is not optimized (e.g., features are not normalized), also the datasets for the competition are different. That said, I would still recommend you continue using this code as a reference, as it is quite more re-usable. Following the "How to" guide may be useful to optimize it (README [[here](https://github.com/BNN-UPC/GNNetworkingChallenge/tree/2021_Routenet_TF)]).

Aside from that, the input of RouteNet is the traffic volume generated (not necessarily received) at each src-dst pair. To generate the traffic, we first compute a TM with the formula you mentioned, and use it as an input to the simulator. After the simulation, we take the actual traffic generated on each src-dst pair, which may vary slightly from the input TM values, and use it as an input for RouteNet. This is how we would use RouteNet in real deployments, as we could collect real traffic measurements from the network and use the model to infer some KPIs.

I hope this clarifies your question.

Regards,
José

**Comment by diegocervera** [comment]
José,

Many thanks for you prompt reply. That makes sense.

Regards,
Diego
