### ISSUE TITLE
Problem with the Simulator when changing the Max topology number and the max bandwidth

### ISSUE THREAD

**Issue by sofiane06** [knowledgedefinednetworking/RouteNet-challenge#9]
Hello,

I'm a PHD student and i'm trying to use your model.

I want also to create a custom dataset for the validation and prediction purpose but when the (_**network_size >10 or bandwidth >100000)**_
the simulator does not work properly and returns an exception related to the existence of the folder /data.{ctr} (not created) even i changed the parameters max topology size and max bandwidth in the Simulate.py file.

So my questions are:
-- there are other parameters that i should  change in the simulator?  
-- how did you create your validation dataset (50, 100, 150...nodes)?

thanks in advance for helping.

regards,
Sofiane MESSAOUDI

**Comment by Magnido9** [comment]
Hey, I also had the same problem, would love if you could help us,
thanks

**Comment by albert-lopez** [comment]
Hello,

There is a docker version of the simulator without the limitations imposed by the challenge. You can find instructions to use it in this repository:[https://github.com/BNN-UPC/BNNetSimulator]( https://github.com/BNN-UPC/BNNetSimulator)

Regards

Albert
